# Generated by Django 3.2 on 2021-10-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_h1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Оглавление страницы')),
                ('photo', models.ImageField(upload_to='portfolio/')),
                ('photo_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Описание фото')),
            ],
            options={
                'verbose_name': 'Фотография в портфолио',
                'verbose_name_plural': 'Фотографии в портфолио',
            },
        ),
    ]
