# Generated by Django 3.2 on 2021-10-11 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211011_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='title_h1',
        ),
    ]
