# Generated by Django 3.2 on 2021-10-11 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_portfolio_title_h1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='photo_tumb',
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='photo_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Категория фото'),
        ),
    ]
