# Generated by Django 3.2 on 2021-10-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20211012_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincardmodel',
            name='post_link',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
