# Generated by Django 3.2 on 2021-10-16 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_maincardmodel_post_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='photo',
        ),
        migrations.CreateModel(
            name='PortfolioPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='portfolio', verbose_name='Фотография')),
                ('showphoto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.portfolio')),
            ],
        ),
    ]
