# Generated by Django 3.2 on 2021-10-16 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20211017_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliophoto',
            name='showphoto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.portfolio'),
        ),
    ]
