# Generated by Django 4.0 on 2022-01-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_portfoliophoto_showphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliophoto',
            name='photodesc',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Категория фото'),
        ),
    ]
