# Generated by Django 4.0 on 2022-01-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_portfoliophoto_photodesc'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmorder',
            name='confirm_order_photo',
            field=models.ImageField(default=2, upload_to='', verbose_name='Фотография заказа'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='maincardmodel',
            name='description',
            field=models.TextField(max_length=150, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='portfoliophoto',
            name='photodesc',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Описание фото'),
        ),
    ]
