# Generated by Django 4.0 on 2022-01-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_confirmorder_confirm_order_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmorder',
            name='confirm_order_photo',
        ),
        migrations.AddField(
            model_name='confirmorder',
            name='path',
            field=models.FilePathField(default=2, path='/pictures/'),
            preserve_default=False,
        ),
    ]
