# Generated by Django 4.0 on 2022-01-20 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_confirmorder_confirm_order_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmorder',
            name='image',
        ),
        migrations.RemoveField(
            model_name='confirmorder',
            name='path',
        ),
    ]
