# Generated by Django 4.0 on 2022-01-20 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_confirmorder_image_remove_confirmorder_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmorder',
            name='link',
        ),
    ]
