# Generated by Django 3.2 on 2021-10-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopCardModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='shop-images', verbose_name='Изображение товара')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование товара')),
                ('description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Описание товара')),
                ('category', models.CharField(max_length=100, verbose_name='Категория товара')),
                ('price', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Карточка товара в магазине',
                'verbose_name_plural': 'Карточки товара в магазине',
            },
        ),
    ]
