# Generated by Django 3.2 on 2021-10-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20211016_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcardphotos',
            name='photo',
            field=models.ImageField(upload_to='shop-images', verbose_name='Изображение товара'),
        ),
    ]
