# Generated by Django 3.2 on 2021-10-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_shopcardphotos_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcardphotos',
            name='photo',
            field=models.ImageField(upload_to='shop-photos', verbose_name='Изображение товара'),
        ),
    ]
