# Generated by Django 3.2 on 2021-10-16 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_shopcardphotos_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopcardphotos',
            old_name='photo',
            new_name='photos',
        ),
    ]
