# Generated by Django 3.2 on 2021-10-16 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_rename_photo_shopcardphotos_photos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopcardphotos',
            old_name='photos',
            new_name='photo',
        ),
    ]
