# Generated by Django 3.2 on 2021-10-16 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_rename_photos_shopcardphotos_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopcardmodel',
            options={'verbose_name': 'Товар в магазине', 'verbose_name_plural': 'Товар в магазине'},
        ),
    ]
